/**
 * generator.ts
 * ------------------------------------------------------------------
 * Takes the fully-assembled ProjectContext object and renders it
 * into a single, clean, token-optimized Markdown document. This is
 * the file developers paste into ChatGPT/Claude/Cursor, or point
 * their AI coding assistant at directly.
 *
 * Design principles for token efficiency:
 *   - No decorative filler, emojis kept minimal, tight tables
 *   - Dependencies shown as compact "name@version" lists, not prose
 *   - File previews are capped and clearly marked as truncated
 * ------------------------------------------------------------------
 */
import { ProjectContext } from "./types";
import { renderTree } from "./treeBuilder";
import { estimateTokens, formatTokenBudgetNote } from "./tokenEstimator";

export function generateMarkdown(ctx: ProjectContext): string {
  // Body sections are built first so we can measure their real size for
  // the token estimate, then the header (which reports that estimate)
  // is prepended. The header's own overhead is a few dozen tokens and
  // is intentionally left out of the measurement - see tokenEstimator.ts.
  const bodySections: string[] = [];

  bodySections.push(renderTreeSection(ctx));
  if (ctx.pkg) bodySections.push(renderPackageSection(ctx));
  if (ctx.envVars.length > 0) bodySections.push(renderEnvSection(ctx));
  if (ctx.schemas.length > 0) bodySections.push(renderSchemaSection(ctx));
  if (ctx.symbols.length > 0) bodySections.push(renderSymbolsSection(ctx));
  if (ctx.imports.length > 0) bodySections.push(renderImportsSection(ctx));
  if (ctx.keyFiles.length > 0) bodySections.push(renderKeyFilesSection(ctx));
  bodySections.push(renderFooter());

  const body = bodySections.join("\n\n");
  const tokenStats = estimateTokens(body);
  ctx.tokenStats = tokenStats;

  const header = renderHeader(ctx);

  return header + "\n\n" + body + "\n";
}

function renderHeader(ctx: ProjectContext): string {
  const lines = [
    `# Project Context: ${ctx.rootName}`,
    "",
    `> Auto-generated by [ctx-gen](https://github.com/yourname/ctx-gen) on ${ctx.generatedAt}.`,
    `> Feed this file to your AI coding assistant for full project awareness.`,
    "",
    `**Files:** ${ctx.fileCount}  |  **Directories:** ${ctx.dirCount}`,
  ];

  if (ctx.tokenStats) {
    lines.push(`**Context size:** ${formatTokenBudgetNote(ctx.tokenStats.approxTokens)}`);
  }

  return lines.join("\n");
}

function renderTreeSection(ctx: ProjectContext): string {
  return ["## 📁 File Structure", "", "```", renderTree(ctx.tree), "```"].join("\n");
}

function renderPackageSection(ctx: ProjectContext): string {
  const pkg = ctx.pkg!;
  const lines: string[] = ["## 📦 Project Info", ""];

  if (pkg.name) lines.push(`- **Name:** ${pkg.name}`);
  if (pkg.version) lines.push(`- **Version:** ${pkg.version}`);
  if (pkg.description) lines.push(`- **Description:** ${pkg.description}`);
  if (pkg.main) lines.push(`- **Entry point:** ${pkg.main}`);
  if (pkg.type) lines.push(`- **Module type:** ${pkg.type}`);

  if (pkg.scripts && Object.keys(pkg.scripts).length > 0) {
    lines.push("", "**Scripts:**", "```json", JSON.stringify(pkg.scripts, null, 2), "```");
  }

  const depCount = Object.keys(pkg.dependencies ?? {}).length;
  const devDepCount = Object.keys(pkg.devDependencies ?? {}).length;

  if (depCount > 0) {
    lines.push("", `**Dependencies (${depCount}):**`);
    lines.push(formatDepList(pkg.dependencies!));
  }
  if (devDepCount > 0) {
    lines.push("", `**Dev Dependencies (${devDepCount}):**`);
    lines.push(formatDepList(pkg.devDependencies!));
  }

  return lines.join("\n");
}

function formatDepList(deps: Record<string, string>): string {
  // Compact comma-separated "name@version" list - far fewer tokens than a table
  return Object.entries(deps)
    .map(([name, version]) => `\`${name}@${version}\``)
    .join(", ");
}

function renderEnvSection(ctx: ProjectContext): string {
  const lines = ["## 🔑 Environment Variables", "", "| Variable | Purpose |", "|---|---|"];
  for (const entry of ctx.envVars) {
    lines.push(`| \`${entry.key}\` | ${entry.comment ?? "—"} |`);
  }
  return lines.join("\n");
}

function renderSchemaSection(ctx: ProjectContext): string {
  const lines = ["## 🗄️ Database Schema", ""];
  for (const schema of ctx.schemas) {
    lines.push(`**${schema.sourceFile}** (${schema.kind}):`);
    lines.push(schema.models.map((m) => `\`${m}\``).join(", "));
    lines.push("");
  }
  return lines.join("\n").trimEnd();
}

function renderKeyFilesSection(ctx: ProjectContext): string {
  const lines = ["## 🚪 Key Entry Points", ""];
  for (const file of ctx.keyFiles) {
    lines.push(`### ${file.relPath}`);
    lines.push("```" + file.language);
    lines.push(file.lines.join("\n"));
    if (file.truncated) lines.push("// ... truncated ...");
    lines.push("```");
    lines.push("");
  }
  return lines.join("\n").trimEnd();
}

function renderSymbolsSection(ctx: ProjectContext): string {
  const lines = ["## 🧩 Code Symbols", ""];

  for (const file of ctx.symbols) {
    lines.push(`### ${file.relPath}`);
    for (const sym of file.symbols) {
      const icon = sym.kind === "class" ? "🏛️" : sym.kind === "route" ? "🌐" : "ƒ";
      lines.push(`- ${icon} \`${sym.signature}\`  <sub>L${sym.line}</sub>`);
    }
    if (file.truncated) lines.push(`- _... additional symbols truncated ..._`);
    lines.push("");
  }

  return lines.join("\n").trimEnd();
}

function renderImportsSection(ctx: ProjectContext): string {
  const lines = [
    "## 🔗 Import Graph",
    "",
    "_Internal file-to-file connections only. External packages are already listed under Project Info._",
    "",
  ];

  for (const file of ctx.imports) {
    const targets = file.internal.map((t) => `\`${t}\``).join(", ");
    const externalNote = file.externalCount > 0 ? ` _(+${file.externalCount} external)_` : "";
    lines.push(`- **${file.relPath}** → ${targets}${externalNote}`);
  }

  return lines.join("\n");
}

function renderFooter(): string {
  return [
    "---",
    "*Generated by ctx-gen — a local, offline context engine for AI coding assistants. " +
      "No code ever leaves your machine.*",
  ].join("\n");
}
